// Companies whose name starts with "W".
// India-based / India-hiring companies are listed first (priority per request),
// then global MNCs — most of which run large engineering centres in India
// (Bangalore, Hyderabad, Pune, Chennai, Noida, Gurugram).
//
// Fields:
//   name    - display name
//   country - HQ / primary hiring geo
//   site    - primary domain (used to auto-derive careers URL candidates)
//   careers - known careers page (optional; discovery also guesses)
//   ats     - known ATS hints: { type, token, host?, site?, wd? } (optional)
//
// ATS hints are only a head start: test.js sniffs the careers page itself for
// 25+ platforms, and every guessed token is validated against the board's own
// company name before its jobs are accepted.

module.exports = [
  // ================================================================ INDIA (1-45)
  { name: 'Wipro',                    country: 'India', site: 'wipro.com',              careers: 'https://careers.wipro.com/careers-home', ats: { type: 'successfactors', token: 'wipro', host: 'https://careers.wipro.com' } },
  { name: 'WNS Global Services',      country: 'India', site: 'wns.com',                careers: 'https://www.wnscareers.com/global-location/india', ats: { type: 'smartrecruiters', token: 'WNSGlobalServices144' } },
  { name: 'Whatfix',                  country: 'India', site: 'whatfix.com',            careers: 'https://whatfix.com/careers/', ats: { type: 'recruiterbox', token: 'whatfix101' } },
  { name: 'Wissen Technology',        country: 'India', site: 'wissen.com',             careers: 'https://www.wissen.com/career/opportunities-wissen-technology', ats: { type: 'zohorecruit', token: 'wissen', host: 'https://wissen.zohorecruit.in' } },
  { name: 'Wingify (VWO)',            country: 'India', site: 'wingify.com',            careers: 'https://wingify.keka.com/careers', ats: { type: 'keka', token: 'wingify', portal: 'default' } },
  { name: 'WebEngage',                country: 'India', site: 'webengage.com',          careers: 'https://webengage.com/careers/' },
  { name: 'WazirX',                   country: 'India', site: 'wazirx.com',             careers: 'https://careers.wazirx.com/' },
  { name: 'Wakefit',                  country: 'India', site: 'wakefit.co',             careers: 'https://wakefit.darwinbox.in/ms/candidate/careers', ats: { type: 'instahyre', token: 'Wakefit', host: 'https://www.instahyre.com' } },
  { name: 'WheelsEye',                country: 'India', site: 'wheelseye.com',          careers: 'https://www.wheelseye.com/careers', ats: { type: 'instahyre', token: 'WheelsEye', host: 'https://www.instahyre.com' } },
  { name: 'WinZO Games',              country: 'India', site: 'winzogames.com',         careers: 'https://winzo.keka.com/careers', ats: { type: 'keka', token: 'winzo', portal: 'default' } },
  { name: 'WayCool Foods',            country: 'India', site: 'waycool.in',             careers: 'https://www.waycool.in/' },
  { name: 'Webkul Software',          country: 'India', site: 'webkul.com',             careers: 'https://webkul.com/career/' },
  { name: 'Winjit Technologies',      country: 'India', site: 'winjit.com',             careers: 'https://winjit.hire.trakstar.com/jobs', ats: { type: 'recruiterbox', token: 'winjit', host: 'https://winjit.hire.trakstar.com' } },
  { name: 'WovV Technologies',        country: 'India', site: 'wovvtech.com',           careers: 'https://wovvtech.com/careers/' },
  { name: 'WorkIndia',                country: 'India', site: 'workindia.in',           careers: 'https://www.workindia.in/careers/' },
  { name: 'Wysa',                     country: 'India', site: 'wysa.com',               careers: 'https://www.wysa.com/careers' },
  { name: 'Wobot AI',                 country: 'India', site: 'wobot.ai',               careers: 'https://wobot.ai/careers', ats: { type: 'cvviz', token: '1758', host: 'https://jobs.cvviz.com', slug: 'wobot_intelligence_pvt_ltd' } },
  { name: 'Webandcrafts',             country: 'India', site: 'webandcrafts.com',       careers: 'https://webandcrafts.com/careers' },
  { name: 'Wolken Software',          country: 'India', site: 'wolkensoftware.com',     careers: 'https://wolken.keka.com/careers/', ats: { type: 'keka', token: 'wolken', host: 'https://wolken.keka.com' } },
  { name: 'Wibmo (PayU)',             country: 'India', site: 'wibmo.com',              careers: 'https://www.wibmo.com/careers/' },
  { name: 'Wockhardt',                country: 'India', site: 'wockhardt.com',          careers: 'https://www.wockhardt.com/careers/' },
  { name: 'Welspun World',            country: 'India', site: 'welspun.com',            careers: 'https://welpro.welspun.com/careers' },
  { name: 'Whirlpool of India',       country: 'India', site: 'whirlpoolindia.com',     careers: 'https://jobs.whirlpool.com/careers?domain=whirlpool.com&location=India', ats: { type: 'eightfold', token: 'whirlpool', host: 'https://jobs.whirlpool.com', domain: 'whirlpool.com' } },
  { name: 'Wonderla Holidays',        country: 'India', site: 'wonderla.com',           careers: 'https://www.wonderla.com/careers' },
  { name: 'Wonderchef',               country: 'India', site: 'wonderchef.com',         careers: 'https://www.wonderchef.com/pages/careers' },
  { name: 'Wow Skin Science',         country: 'India', site: 'buywow.in',              careers: 'https://www.buywow.in/pages/careers' },
  { name: 'Wow! Momo Foods',          country: 'India', site: 'wowmomo.in',             careers: 'https://www.wowmomo.com/careers' },
  { name: 'Wint Wealth',              country: 'India', site: 'wintwealth.com',         careers: 'https://www.wintwealth.com/careers' },
  { name: 'Weekday.works',            country: 'India', site: 'weekday.works',          careers: 'https://www.weekday.works/careers' },
  { name: 'Wizikey',                  country: 'India', site: 'wizikey.com',            careers: 'https://www.wizikey.com/careers' },
  { name: 'Wadhwani AI',              country: 'India', site: 'wadhwaniai.org',         careers: 'https://www.wadhwaniai.org/careers/' },
  { name: 'Wellthy Therapeutics',     country: 'India', site: 'wellthytherapeutics.com', careers: 'https://www.wellthytherapeutics.com/careers/' },
  { name: 'Wavelabs Technologies',    country: 'India', site: 'wavelabs.ai',            careers: 'https://www.veltris.com/careers/', ats: { type: 'zohorecruit', token: 'veltris', host: 'https://veltris.zohorecruit.com' } },
  { name: 'Wipro PARI',               country: 'India', site: 'wipropari.com',          careers: 'https://www.wipropari.com/careers/' },
  { name: 'Waterfield Advisors',      country: 'India', site: 'waterfieldadvisors.com', careers: 'https://waterfieldadvisors.com/careers/' },
  { name: 'WeMakeScholars',           country: 'India', site: 'wemakescholars.com',     careers: 'https://www.wemakescholars.com/hiring' },
  { name: 'Wheelocity',               country: 'India', site: 'wheelocity.in',          careers: 'https://wheelocity.in/careers' },
  { name: 'Wingreens World',          country: 'India', site: 'wingreensworld.com',     careers: 'https://wingreensworld.com/pages/careers' },
  { name: 'WoodenStreet',             country: 'India', site: 'woodenstreet.com',       careers: 'https://www.woodenstreet.com/careers' },
  { name: 'Winman Software',          country: 'India', site: 'winmansoftware.com',     careers: 'https://www.winmansoftware.com/careers' },
  { name: 'WeWork India',             country: 'India', site: 'wework.co.in',           careers: 'https://wework.co.in/careers/' },
  { name: 'Wingify Earth',            country: 'India', site: 'wingifyearth.com',       careers: 'https://wingifyearth.com/careers' },
  { name: 'Wholsum Foods (Slurrp)',   country: 'India', site: 'slurrpfarm.com',         careers: 'https://slurrpfarm.com/pages/careers' },
  { name: 'Wiom',                     country: 'India', site: 'wiom.in',                careers: 'https://wiom.in/careers' },
  { name: 'Wizcraft',                 country: 'India', site: 'wizcraftworld.com',      careers: 'https://www.wizcraftworld.com/careers' },

  // ====================================== GLOBAL MNCs WITH LARGE INDIA CENTRES (46-95)
  { name: 'Walmart Global Tech',      country: 'USA',   site: 'walmart.com',            careers: 'https://careers.walmart.com/technology' },
  { name: 'Wells Fargo',              country: 'USA',   site: 'wellsfargo.com',         careers: 'https://wf.wd1.myworkdayjobs.com/en-US/WellsFargoJobs', ats: { type: 'workday', token: 'wf', wd: 'wd1', site: 'WellsFargoJobs', host: 'https://wf.wd1.myworkdayjobs.com' } },
  { name: 'Workday',                  country: 'USA',   site: 'workday.com',            careers: 'https://www.workday.com/en-us/company/careers.html' },
  { name: 'Western Digital',          country: 'USA',   site: 'westerndigital.com',     careers: 'https://jobs.westerndigital.com/' },
  { name: 'Wolters Kluwer',           country: 'Netherlands', site: 'wolterskluwer.com', careers: 'https://jobs.wolterskluwer.com/' },
  { name: 'Wayfair',                  country: 'USA',   site: 'wayfair.com',            careers: 'https://www.wayfair.com/careers/jobs', ats: { type: 'avature', token: 'wayfair' } },
  { name: 'Warner Bros. Discovery',   country: 'USA',   site: 'wbd.com',                careers: 'https://careers.wbd.com/global/en/search-results' },
  { name: 'Western Union',            country: 'USA',   site: 'westernunion.com',       careers: 'https://careers.westernunion.com/' },
  { name: 'WTW (Willis Towers Watson)', country: 'UK',  site: 'wtwco.com',              careers: 'https://careers.wtwco.com/' },
  { name: 'Wabtec',                   country: 'USA',   site: 'wabtec.com',             careers: 'https://careers.wabtec.com/' },
  { name: 'Waters Corporation',       country: 'USA',   site: 'waters.com',             careers: 'https://uscareers-waters.icims.com/jobs/search?ss=1&in_iframe=1', ats: { type: 'icims', token: 'uscareers-waters' } },
  { name: 'Whirlpool Corporation',    country: 'USA',   site: 'whirlpool.com',          careers: 'https://jobs.whirlpool.com/careers?domain=whirlpool.com', ats: { type: 'eightfold', token: 'whirlpool', host: 'https://jobs.whirlpool.com', domain: 'whirlpool.com' } },
  { name: 'Wiley',                    country: 'USA',   site: 'wiley.com',              careers: 'https://careers.wiley.com/' },
  { name: 'Worley',                   country: 'Australia', site: 'worley.com',         careers: 'https://www.worley.com/en/careers' },
  { name: 'WSP',                      country: 'Canada', site: 'wsp.com',               careers: 'https://emit.fa.ca3.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001/', ats: { type: 'oracleorc', token: 'CX_2001', host: 'https://emit.fa.ca3.oraclecloud.com', siteNumber: 'CX_2001', site: 'CX_2001' } },
  { name: 'Wood',                     country: 'UK',    site: 'woodplc.com',            careers: 'https://www.woodplc.com/careers' },
  { name: 'World Wide Technology',    country: 'USA',   site: 'wwt.com',                careers: 'https://myjobs.adp.com/wwtexternalcareersite', ats: { type: 'adp', token: 'wwtexternalcareersite', orgoid: 'G3EZHP2WRRMJSRJM' } },
  { name: 'WEX Inc.',                 country: 'USA',   site: 'wexinc.com',             careers: 'https://www.wexinc.com/careers/' },
  { name: 'Welocalize',               country: 'USA',   site: 'welocalize.com',         careers: 'https://www.welocalize.com/careers/' },
  { name: 'Wärtsilä',                 country: 'Finland', site: 'wartsila.com',         careers: 'https://www.wartsila.com/careers' },
  { name: 'Woodward',                 country: 'USA',   site: 'woodward.com',           careers: 'https://www.woodward.com/careers' },
  { name: 'Wistron',                  country: 'Taiwan', site: 'wistron.com',           careers: 'https://jobs.wistron.com/#/app/vacancy' },
  { name: 'Wacker Chemie',            country: 'Germany', site: 'wacker.com',           careers: 'https://www.wacker.com/cms/en-us/careers/careers.html' },
  { name: 'WM (Waste Management)',    country: 'USA',   site: 'wm.com',                 careers: 'https://careers.wm.com/', ats: { type: 'oracleorc', token: 'WMCareers', site: 'CX_4001', host: 'https://emcm.fa.us2.oraclecloud.com', siteNumber: 'CX_4001' } },
  { name: 'Williams-Sonoma',          country: 'USA',   site: 'williams-sonoma.com',    careers: 'https://www.williams-sonomainc.com/careers/jobs/', ats: { type: 'oracleorc', token: 'ehac', site: 'CX_1', host: 'https://ehac.fa.us6.oraclecloud.com' } },
  { name: 'WPP',                      country: 'UK',    site: 'wpp.com',                careers: 'https://www.wpp.com/en/careers/search-and-apply', ats: { type: 'greenhouse', token: 'wpp' } },
  { name: 'Workhuman',                country: 'Ireland', site: 'workhuman.com',        careers: 'https://www.workhuman.com/careers/' },
  { name: 'Westinghouse Electric',    country: 'USA',   site: 'westinghousenuclear.com', careers: 'https://westinghousenuclear.com/careers/' },
  { name: 'Weir Group',               country: 'UK',    site: 'global.weir',            careers: 'https://www.global.weir/careers/' },
  { name: 'Wolfspeed',                country: 'USA',   site: 'wolfspeed.com',          careers: 'https://www.wolfspeed.com/careers/' },
  { name: 'Winnebago Industries',     country: 'USA',   site: 'winnebago.com',          careers: 'https://www.winnebagoind.com/careers', ats: { type: 'adp', token: '82c90207-af7d-495b-b437-aa9a4c72f4e8', host: 'https://workforcenow.adp.com', cid: '82c90207-af7d-495b-b437-aa9a4c72f4e8' } },
  { name: 'Woodside Energy',          country: 'Australia', site: 'woodside.com',       careers: 'https://careers.woodside.com.au/', ats: { type: 'successfactors', token: 'https://careers.woodside.com.au', host: 'https://careers.woodside.com.au' } },
  { name: 'Wienerberger',             country: 'Austria', site: 'wienerberger.com',     careers: 'https://wienerberger.csod.com/ux/ats/careersite/4/home?c=wienerberger&lang=en-US' },
  { name: 'Würth Group',              country: 'Germany', site: 'wuerth.com',           careers: 'https://career.witglobal.net/search/?q=&locationsearch=&locale=en_US&searchResultView=LIST', ats: { type: 'successfactors', token: 'career.witglobal.net', host: 'https://career.witglobal.net' } },
  { name: 'WAGO',                     country: 'Germany', site: 'wago.com',             careers: 'https://www.wago.com/de/jobs' },
  { name: 'Wacom',                    country: 'Japan', site: 'wacom.com',              careers: 'https://www.wacom.com/en-us/about-wacom/careers-at-wacom' },
  { name: 'Warner Music Group',       country: 'USA',   site: 'wmg.com',                careers: 'https://www.wmg.com/careers' },
  { name: 'Wendy\'s',                 country: 'USA',   site: 'wendys.com',             careers: 'https://wendys-careers.com/job-search/' },
  { name: 'Wingstop',                 country: 'USA',   site: 'wingstop.com',           careers: 'https://www.wingstopcareers.com/' },
  { name: 'Whitbread',                country: 'UK',    site: 'whitbread.co.uk',        careers: 'https://www.whitbreadcareers.com/search-and-apply/' },
  { name: 'WH Smith',                 country: 'UK',    site: 'whsmith.co.uk',          careers: 'https://www.whsmithcareers.co.uk/' },
  { name: 'Webhelp (Concentrix)',     country: 'France', site: 'webhelp.com',           careers: 'https://jobs.concentrix.com/', ats: { type: 'workday', token: 'cnx', wd: 'wd1', site: 'external_global', host: 'https://cnx.wd1.myworkdayjobs.com' } },
  { name: 'Wolseley',                 country: 'UK',    site: 'wolseley.co.uk',         careers: 'https://www.wolseleycareers.co.uk/', ats: { type: 'workday', token: 'wolseleyuk', wd: 'wd3', site: 'Wolseley', host: 'https://wolseleyuk.wd3.myworkdayjobs.com' } },
  { name: 'Wesco International',      country: 'USA',   site: 'wesco.com',              careers: 'https://eklm.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX/jobs', ats: { type: 'oracleorc', token: 'eklm', host: 'https://eklm.fa.us2.oraclecloud.com', siteNumber: 'CX', site: 'CX' } },
  { name: 'Westlake Corporation',     country: 'USA',   site: 'westlake.com',           careers: 'https://www.westlaketalent.com/jobs' },
  { name: 'WestRock (Smurfit)',       country: 'USA',   site: 'westrock.com',           careers: 'https://smurfitwestrockta.avature.net/en_US/careers/SearchJobs', ats: { type: 'avature', token: 'smurfitwestrockta', host: 'https://smurfitwestrockta.avature.net', locale: 'en_US' } },
  { name: 'Willdan Group',            country: 'USA',   site: 'willdan.com',            careers: 'https://www.willdan.com/careers' },
  { name: 'Watts Water Technologies', country: 'USA',   site: 'watts.com',              careers: 'https://wattswater.wd5.myworkdayjobs.com/External', ats: { type: 'workday', token: 'wattswater', wd: 'wd5', site: 'External', host: 'https://wattswater.wd5.myworkdayjobs.com' } },
  { name: 'Westpac',                  country: 'Australia', site: 'westpac.com.au',     careers: 'https://www.westpac.com.au/about-westpac/careers/' },
  { name: 'Wesfarmers',               country: 'Australia', site: 'wesfarmers.com.au',  careers: 'https://www.wesfarmers.com.au/util/careers/corporate-careers/current-opportunities-lh' },

  // ============================================ GLOBAL TECH / PRODUCT (96-120)
  { name: 'Wiz',                      country: 'USA',   site: 'wiz.io',                 careers: 'https://www.wiz.io/careers',        ats: { type: 'greenhouse', token: 'wizinc' } },
  { name: 'Workato',                  country: 'USA',   site: 'workato.com',            careers: 'https://www.workato.com/careers',   ats: { type: 'greenhouse', token: 'workato' } },
  { name: 'Webflow',                  country: 'USA',   site: 'webflow.com',            careers: 'https://webflow.com/careers',       ats: { type: 'greenhouse', token: 'webflow' } },
  { name: 'Wealthfront',              country: 'USA',   site: 'wealthfront.com',        careers: 'https://www.wealthfront.com/careers', ats: { type: 'lever', token: 'wealthfront' } },
  { name: 'WHOOP',                    country: 'USA',   site: 'whoop.com',              careers: 'https://www.whoop.com/careers/',    ats: { type: 'ashby', token: 'whoop' } },
  { name: 'Weights & Biases',         country: 'USA',   site: 'wandb.com',              careers: 'https://wandb.ai/site/careers',     ats: { type: 'greenhouse', token: 'weightsandbiases' } },
  { name: 'Wrike',                    country: 'USA',   site: 'wrike.com',              careers: 'https://www.wrike.com/careers/',    ats: { type: 'greenhouse', token: 'wrike' } },
  { name: 'WP Engine',                country: 'USA',   site: 'wpengine.com',           careers: 'https://wpengine.careers/',         ats: { type: 'workday', token: 'wpengine', wd: 'wd1', site: 'WP_Engine' } },
  { name: 'WalkMe',                   country: 'Israel', site: 'walkme.com',            careers: 'https://www.walkme.com/careers/', ats: { type: 'lever', token: 'walkme' } },
  { name: 'Wistia',                   country: 'USA',   site: 'wistia.com',             careers: 'https://wistia.com/about/careers', ats: { type: 'ashby', token: 'wistia' } },
  { name: 'Wattpad',                  country: 'Canada', site: 'wattpad.com',           careers: 'https://company.wattpad.com/careers' },
  { name: 'Workiva',                  country: 'USA',   site: 'workiva.com',            careers: 'https://www.workiva.com/careers', ats: { type: 'workday', token: 'workiva', wd: 'wd503', site: 'careers' } },
  { name: 'Wise',                     country: 'UK',    site: 'wise.com',               careers: 'https://www.wise.jobs/', ats: { type: 'smartrecruiters', token: 'Wise' } },
  { name: 'Wix.com',                  country: 'Israel', site: 'wix.com',               careers: 'https://careers.wix.com/positions', ats: { type: 'smartrecruiters', token: 'Wix2' } },
  { name: 'Wolt (DoorDash)',          country: 'Finland', site: 'wolt.com',             careers: 'https://careers.wolt.com/en/jobs' },
  { name: 'WeTransfer (Bending Spoons)', country: 'Netherlands', site: 'wetransfer.com', careers: 'https://bendingspoons.com/careers' },
  { name: 'Workvivo (Zoom)',          country: 'Ireland', site: 'workvivo.com',         careers: 'https://careers.zoom.us/jobs/search?page=1&dropdown_field_1_uids%5B%5D=ec44169900cf4b446f24bd736385eb3d&query=' },
  { name: 'WEKA',                     country: 'USA',   site: 'weka.io',                careers: 'https://www.weka.io/careers/' },
  { name: 'Wallarm',                  country: 'USA',   site: 'wallarm.com',            careers: 'https://www.wallarm.com/company/careers' },
  { name: 'WatchGuard Technologies',  country: 'USA',   site: 'watchguard.com',         careers: 'https://www.watchguard.com/wgrd-careers' },
  { name: 'Wolfram Research',         country: 'USA',   site: 'wolfram.com',            careers: 'https://www.wolfram.com/company/careers/opportunities/', ats: { type: 'recruiterbox', token: 'wolframresearch', host: 'https://wolframresearch.hire.trakstar.com' } },
  { name: 'Waymo',                    country: 'USA',   site: 'waymo.com',              careers: 'https://waymo.com/careers/' },
  { name: 'WeWork',                   country: 'USA',   site: 'wework.com',             careers: 'https://wework.wd1.myworkdayjobs.com/WeWork', ats: { type: 'workday', token: 'wework', wd: 'wd1', site: 'WeWork', host: 'https://wework.wd1.myworkdayjobs.com' } },
  { name: 'Wayve',                    country: 'UK',    site: 'wayve.ai',               careers: 'https://wayve.ai/careers/' },
  { name: 'Wefox',                    country: 'Germany', site: 'wefox.com',            careers: 'https://join.com/companies/wefoxgroup' },
  { name: 'Wallbox',                  country: 'Spain', site: 'wallbox.com',            careers: 'https://wallbox.com/en_us/careers' },
  { name: 'Wildlife Studios',         country: 'Brazil', site: 'wildlifestudios.com',   careers: 'https://wildlifestudios.com/careers/' },
  { name: 'Workleap',                 country: 'Canada', site: 'workleap.com',          careers: 'https://www.workleap.com/careers' },
  { name: 'Withings',                 country: 'France', site: 'withings.com',          careers: 'https://apply.workable.com/withings/', ats: { type: 'workable', token: 'withings' } },
  { name: 'Wooga',                    country: 'Germany', site: 'wooga.com',            careers: 'https://www.wooga.com/jobs' },
];
